import type { Exercise, ExerciseCategory } from "./types";

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  respiracion: "Respiración",
  ansiedad: "Regulación de ansiedad",
  desescalada: "Desescalada",
  sueno: "Higiene del sueño",
  diario: "Diario emocional",
  relaciones: "Reflexión sobre relaciones",
};

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: "resp-478",
    title: "Respiración 4-7-8",
    category: "respiracion",
    minutes: 5,
    description:
      "Una respiración pausada que ayuda a reducir la activación física cuando la ansiedad aparece.",
    instructions: [
      "Siéntate con la espalda apoyada y los pies en el suelo.",
      "Inhala por la nariz contando hasta 4.",
      "Retén el aire contando hasta 7.",
      "Suelta el aire por la boca contando hasta 8.",
      "Repite el ciclo entre 4 y 6 veces.",
    ],
    areas: ["ansiedad", "animo"],
  },
  {
    id: "resp-diafragma",
    title: "Respiración diafragmática",
    category: "respiracion",
    minutes: 7,
    description: "Respirar con el abdomen para bajar el ritmo cardiaco y recuperar sensación de calma.",
    instructions: [
      "Coloca una mano en el pecho y otra en el abdomen.",
      "Inhala lentamente notando cómo se eleva solo la mano del abdomen.",
      "Exhala el doble de lento de lo que has inhalado.",
      "Mantén el ritmo durante 5-7 minutos.",
    ],
    areas: ["ansiedad", "relaciones"],
  },
  {
    id: "anx-54321",
    title: "Anclaje 5-4-3-2-1",
    category: "ansiedad",
    minutes: 4,
    description: "Ejercicio de anclaje sensorial para volver al presente cuando la mente se dispara.",
    instructions: [
      "Nombra 5 cosas que puedes ver.",
      "Nombra 4 cosas que puedes tocar.",
      "Nombra 3 sonidos que puedes oír.",
      "Nombra 2 olores que puedes percibir.",
      "Nombra 1 cosa que puedes saborear.",
    ],
    areas: ["ansiedad"],
  },
  {
    id: "anx-preocupacion",
    title: "Tiempo de preocupación",
    category: "ansiedad",
    minutes: 15,
    description:
      "Reservar un espacio acotado del día para las preocupaciones en lugar de dejarlas invadirlo todo.",
    instructions: [
      "Elige una franja fija de 15 minutos al día.",
      "Cuando aparezca una preocupación fuera de esa franja, anótala y aplázala.",
      "En la franja, repasa la lista y separa lo que depende de ti de lo que no.",
      "Define un solo paso concreto para lo que sí depende de ti.",
    ],
    areas: ["ansiedad", "animo"],
  },
  {
    id: "des-stop",
    title: "Pausa STOP",
    category: "desescalada",
    minutes: 3,
    description: "Una pausa breve para no reaccionar en caliente cuando la tensión sube.",
    instructions: [
      "Para lo que estés haciendo.",
      "Toma una respiración lenta y completa.",
      "Observa qué sientes en el cuerpo y qué piensas.",
      "Procede eligiendo la respuesta, no la reacción.",
    ],
    areas: ["ansiedad", "relaciones"],
  },
  {
    id: "des-relajacion",
    title: "Relajación muscular progresiva",
    category: "desescalada",
    minutes: 12,
    description: "Tensar y soltar grupos musculares para liberar la tensión acumulada.",
    instructions: [
      "Tensa los pies durante 5 segundos y suelta.",
      "Sube por piernas, abdomen, manos, brazos, hombros y cara.",
      "Deja 10 segundos de descanso entre grupos.",
      "Termina con tres respiraciones lentas.",
    ],
    areas: ["ansiedad", "animo"],
  },
  {
    id: "sueno-rutina",
    title: "Rutina de cierre del día",
    category: "sueno",
    minutes: 20,
    description: "Preparar el cuerpo y la mente para dormir con una secuencia estable.",
    instructions: [
      "Fija una hora de acostarte y respétala también los fines de semana.",
      "Baja las luces y deja las pantallas la última hora.",
      "Anota lo pendiente para mañana y ciérralo.",
      "Haz algo tranquilo: lectura, estiramientos suaves o música.",
    ],
    areas: ["ansiedad", "animo"],
  },
  {
    id: "sueno-despertares",
    title: "Qué hacer si te despiertas",
    category: "sueno",
    minutes: 10,
    description: "Pauta para los despertares nocturnos sin alimentar la frustración.",
    instructions: [
      "Si llevas más de 20 minutos despierto/a, levántate.",
      "Ve a otra habitación con luz tenue y haz algo aburrido.",
      "Vuelve a la cama solo cuando notes sueño.",
      "Evita mirar la hora durante la noche.",
    ],
    areas: ["ansiedad", "animo"],
  },
  {
    id: "diario-emocional",
    title: "Diario emocional",
    category: "diario",
    minutes: 10,
    description: "Poner palabras a lo que sientes reduce su intensidad y ayuda a ver patrones.",
    instructions: [
      "Describe la situación en dos líneas.",
      "Nombra la emoción y su intensidad del 0 al 10.",
      "Anota el pensamiento que apareció.",
      "Escribe una forma alternativa y más amable de mirarlo.",
    ],
    areas: ["animo", "relaciones", "ansiedad"],
  },
  {
    id: "diario-agradecimiento",
    title: "Tres cosas del día",
    category: "diario",
    minutes: 5,
    description: "Entrenar la atención hacia lo que sí funciona, sin negar lo difícil.",
    instructions: [
      "Cada noche anota tres cosas concretas del día.",
      "Explica brevemente por qué cada una te importó.",
      "Repítelo durante al menos dos semanas.",
    ],
    areas: ["animo"],
  },
  {
    id: "rel-necesidades",
    title: "Mapa de necesidades",
    category: "relaciones",
    minutes: 15,
    description: "Identificar qué necesitas de un vínculo antes de conversarlo.",
    instructions: [
      "Escribe qué te duele de la situación actual.",
      "Traduce ese dolor en una necesidad concreta.",
      "Formula una petición clara, en positivo y realizable.",
      "Elige un momento tranquilo para plantearla.",
    ],
    areas: ["relaciones"],
  },
  {
    id: "rel-limites",
    title: "Ensayo de límites",
    category: "relaciones",
    minutes: 10,
    description: "Practicar cómo decir que no sin culpa ni agresividad.",
    instructions: [
      "Escribe la frase con la estructura: 'Cuando… me siento… y necesito…'.",
      "Léela en voz alta dos veces.",
      "Anticipa una respuesta difícil y cómo la sostendrías.",
      "Recuerda que puedes repetir el límite con calma.",
    ],
    areas: ["relaciones", "ansiedad"],
  },
];